apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: azurekube 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: azurekube 
    spec:
      containers:
        - name: azurekube 
          image: jbrepo.azurecr.io/azurekube
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readinesprobe
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1